
#公告设置
[app]
    path            = "/ql" #青龙面板映射文件夹名称,一般为QL或ql
    QLip            = "http://127.0.0.1" #青龙面板的ip
    QLport          = "5700" #青龙面板的端口，默认为5700
    notice          = "使用京东扫描二维码登录，提示升级版本无需理会，直接回到网页，登录成功显示用户名或者提示添加成功即自动上车。添加完第一个账号点退出即可添加第二个账号，切记不可以点删除账号。点左上角消息推送，弹出二维码，微信扫描关注加入即可收取任务完成通知。点击下方即可加入tg交流群" #公告/说明
    pushQr          = "" #消息推送二维码链接
    logName         = "panghu999_jd_scripts_jd_bean_change" #日志脚本名称
    allowAdd        = 0 #是否允许添加账号（0允许1不允许）不允许添加时则只允许已有账号登录
    allowNum        = 100 #允许添加账号的最大数量,-1为不限制
    cookieAutoCheck = 0 #自动检测所有cookie并进行失效删除/禁用，0为不检测，1为失效禁用，2为失效删除(每个小时检测一次)

#web服务设置
[server]
    address         = ":9999" #端口号设置
    serverRoot      = "public" #静态目录设置，请勿更改
    serverAgent     = "JDCookie" #服务端UA

#模板设置
[viewer]
    Delimiters      = ["${", "}"] #模板标签，请勿更改


#cli工具设置
[gfcli]
    [gfcli.build]
        name     = "JDC"
        arch     = "amd64"
        system   = "linux"
        mod      = "none"
        cgo      = 0
        pack     = ""
        version  = "v2.0.2"
        output   = "./bin"
        extra    = ""